// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/federation/proto/v2/federation_v2_draft.proto

package federationv2pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriberUpdate_Action int32

const (
	SubscriberUpdate_ACTION_UNSPECIFIED SubscriberUpdate_Action = 0
	SubscriberUpdate_ACTION_REGISTER    SubscriberUpdate_Action = 1
	SubscriberUpdate_ACTION_DEREGISTER  SubscriberUpdate_Action = 2
)

// Enum value maps for SubscriberUpdate_Action.
var (
	SubscriberUpdate_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_REGISTER",
		2: "ACTION_DEREGISTER",
	}
	SubscriberUpdate_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_REGISTER":    1,
		"ACTION_DEREGISTER":  2,
	}
)

func (x SubscriberUpdate_Action) Enum() *SubscriberUpdate_Action {
	p := new(SubscriberUpdate_Action)
	*p = x
	return p
}

func (x SubscriberUpdate_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriberUpdate_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_enumTypes[0].Descriptor()
}

func (SubscriberUpdate_Action) Type() protoreflect.EnumType {
	return &file_internal_federation_proto_v2_federation_v2_draft_proto_enumTypes[0]
}

func (x SubscriberUpdate_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriberUpdate_Action.Descriptor instead.
func (SubscriberUpdate_Action) EnumDescriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{3, 0}
}

type AffiliateUpdate_Action int32

const (
	AffiliateUpdate_ACTION_UNSPECIFIED AffiliateUpdate_Action = 0
	AffiliateUpdate_ACTION_AFFILIATE   AffiliateUpdate_Action = 1
	AffiliateUpdate_ACTION_DEAFFILIATE AffiliateUpdate_Action = 2
)

// Enum value maps for AffiliateUpdate_Action.
var (
	AffiliateUpdate_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "ACTION_AFFILIATE",
		2: "ACTION_DEAFFILIATE",
	}
	AffiliateUpdate_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"ACTION_AFFILIATE":   1,
		"ACTION_DEAFFILIATE": 2,
	}
)

func (x AffiliateUpdate_Action) Enum() *AffiliateUpdate_Action {
	p := new(AffiliateUpdate_Action)
	*p = x
	return p
}

func (x AffiliateUpdate_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AffiliateUpdate_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_enumTypes[1].Descriptor()
}

func (AffiliateUpdate_Action) Type() protoreflect.EnumType {
	return &file_internal_federation_proto_v2_federation_v2_draft_proto_enumTypes[1]
}

func (x AffiliateUpdate_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AffiliateUpdate_Action.Descriptor instead.
func (AffiliateUpdate_Action) EnumDescriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{4, 0}
}

// StreamFrame is the top-level stream item.
type StreamFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*StreamFrame_Control
	//	*StreamFrame_VoiceFrame
	Body          isStreamFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFrame) Reset() {
	*x = StreamFrame{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFrame) ProtoMessage() {}

func (x *StreamFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFrame.ProtoReflect.Descriptor instead.
func (*StreamFrame) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{0}
}

func (x *StreamFrame) GetBody() isStreamFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *StreamFrame) GetControl() *Control {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *StreamFrame) GetVoiceFrame() *VoiceFrame {
	if x != nil {
		if x, ok := x.Body.(*StreamFrame_VoiceFrame); ok {
			return x.VoiceFrame
		}
	}
	return nil
}

type isStreamFrame_Body interface {
	isStreamFrame_Body()
}

type StreamFrame_Control struct {
	Control *Control `protobuf:"bytes,1,opt,name=control,proto3,oneof"`
}

type StreamFrame_VoiceFrame struct {
	VoiceFrame *VoiceFrame `protobuf:"bytes,2,opt,name=voice_frame,json=voiceFrame,proto3,oneof"`
}

func (*StreamFrame_Control) isStreamFrame_Body() {}

func (*StreamFrame_VoiceFrame) isStreamFrame_Body() {}

// Control wraps all non-voice federation messages and carries common
// mesh-routing fields.
type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server name that originated this message.
	Origin string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	// Protocol version announced by sender (for hello/capability checks).
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Mesh routing / deduplication fields.
	MsgId string   `protobuf:"bytes,3,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Ttl   int32    `protobuf:"varint,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Path  []string `protobuf:"bytes,5,rep,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Control_Hello
	//	*Control_SubscriberUpdate
	//	*Control_AffiliateUpdate
	//	*Control_CallStart
	//	*Control_CallEnd
	//	*Control_SdsRelay
	//	*Control_SyncRequest
	//	*Control_SyncResponse
	//	*Control_PeerExchange
	//	*Control_UsersDbOffer
	//	*Control_UsersDbRequest
	//	*Control_PositionSample
	//	*Control_StationUpdate
	Payload       isControl_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{1}
}

func (x *Control) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Control) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Control) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Control) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Control) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Control) GetPayload() isControl_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Control) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Control_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Control) GetSubscriberUpdate() *SubscriberUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Control_SubscriberUpdate); ok {
			return x.SubscriberUpdate
		}
	}
	return nil
}

func (x *Control) GetAffiliateUpdate() *AffiliateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Control_AffiliateUpdate); ok {
			return x.AffiliateUpdate
		}
	}
	return nil
}

func (x *Control) GetCallStart() *CallStart {
	if x != nil {
		if x, ok := x.Payload.(*Control_CallStart); ok {
			return x.CallStart
		}
	}
	return nil
}

func (x *Control) GetCallEnd() *CallEnd {
	if x != nil {
		if x, ok := x.Payload.(*Control_CallEnd); ok {
			return x.CallEnd
		}
	}
	return nil
}

func (x *Control) GetSdsRelay() *SdsRelay {
	if x != nil {
		if x, ok := x.Payload.(*Control_SdsRelay); ok {
			return x.SdsRelay
		}
	}
	return nil
}

func (x *Control) GetSyncRequest() *SyncRequest {
	if x != nil {
		if x, ok := x.Payload.(*Control_SyncRequest); ok {
			return x.SyncRequest
		}
	}
	return nil
}

func (x *Control) GetSyncResponse() *SyncResponse {
	if x != nil {
		if x, ok := x.Payload.(*Control_SyncResponse); ok {
			return x.SyncResponse
		}
	}
	return nil
}

func (x *Control) GetPeerExchange() *PeerExchange {
	if x != nil {
		if x, ok := x.Payload.(*Control_PeerExchange); ok {
			return x.PeerExchange
		}
	}
	return nil
}

func (x *Control) GetUsersDbOffer() *UsersDbOffer {
	if x != nil {
		if x, ok := x.Payload.(*Control_UsersDbOffer); ok {
			return x.UsersDbOffer
		}
	}
	return nil
}

func (x *Control) GetUsersDbRequest() *UsersDbRequest {
	if x != nil {
		if x, ok := x.Payload.(*Control_UsersDbRequest); ok {
			return x.UsersDbRequest
		}
	}
	return nil
}

func (x *Control) GetPositionSample() *PositionSample {
	if x != nil {
		if x, ok := x.Payload.(*Control_PositionSample); ok {
			return x.PositionSample
		}
	}
	return nil
}

func (x *Control) GetStationUpdate() *StationUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Control_StationUpdate); ok {
			return x.StationUpdate
		}
	}
	return nil
}

type isControl_Payload interface {
	isControl_Payload()
}

type Control_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type Control_SubscriberUpdate struct {
	SubscriberUpdate *SubscriberUpdate `protobuf:"bytes,11,opt,name=subscriber_update,json=subscriberUpdate,proto3,oneof"`
}

type Control_AffiliateUpdate struct {
	AffiliateUpdate *AffiliateUpdate `protobuf:"bytes,12,opt,name=affiliate_update,json=affiliateUpdate,proto3,oneof"`
}

type Control_CallStart struct {
	CallStart *CallStart `protobuf:"bytes,13,opt,name=call_start,json=callStart,proto3,oneof"`
}

type Control_CallEnd struct {
	CallEnd *CallEnd `protobuf:"bytes,14,opt,name=call_end,json=callEnd,proto3,oneof"`
}

type Control_SdsRelay struct {
	SdsRelay *SdsRelay `protobuf:"bytes,15,opt,name=sds_relay,json=sdsRelay,proto3,oneof"`
}

type Control_SyncRequest struct {
	SyncRequest *SyncRequest `protobuf:"bytes,16,opt,name=sync_request,json=syncRequest,proto3,oneof"`
}

type Control_SyncResponse struct {
	SyncResponse *SyncResponse `protobuf:"bytes,17,opt,name=sync_response,json=syncResponse,proto3,oneof"`
}

type Control_PeerExchange struct {
	PeerExchange *PeerExchange `protobuf:"bytes,18,opt,name=peer_exchange,json=peerExchange,proto3,oneof"`
}

type Control_UsersDbOffer struct {
	UsersDbOffer *UsersDbOffer `protobuf:"bytes,19,opt,name=users_db_offer,json=usersDbOffer,proto3,oneof"`
}

type Control_UsersDbRequest struct {
	UsersDbRequest *UsersDbRequest `protobuf:"bytes,20,opt,name=users_db_request,json=usersDbRequest,proto3,oneof"`
}

type Control_PositionSample struct {
	PositionSample *PositionSample `protobuf:"bytes,21,opt,name=position_sample,json=positionSample,proto3,oneof"`
}

type Control_StationUpdate struct {
	StationUpdate *StationUpdate `protobuf:"bytes,22,opt,name=station_update,json=stationUpdate,proto3,oneof"`
}

func (*Control_Hello) isControl_Payload() {}

func (*Control_SubscriberUpdate) isControl_Payload() {}

func (*Control_AffiliateUpdate) isControl_Payload() {}

func (*Control_CallStart) isControl_Payload() {}

func (*Control_CallEnd) isControl_Payload() {}

func (*Control_SdsRelay) isControl_Payload() {}

func (*Control_SyncRequest) isControl_Payload() {}

func (*Control_SyncResponse) isControl_Payload() {}

func (*Control_PeerExchange) isControl_Payload() {}

func (*Control_UsersDbOffer) isControl_Payload() {}

func (*Control_UsersDbRequest) isControl_Payload() {}

func (*Control_PositionSample) isControl_Payload() {}

func (*Control_StationUpdate) isControl_Payload() {}

// Hello carries handshake metadata.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional UDP voice parameters for deployments that still use UDP-plane.
	UdpAddr       string `protobuf:"bytes,1,opt,name=udp_addr,json=udpAddr,proto3" json:"udp_addr,omitempty"`
	UdpToken      string `protobuf:"bytes,2,opt,name=udp_token,json=udpToken,proto3" json:"udp_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetUdpAddr() string {
	if x != nil {
		return x.UdpAddr
	}
	return ""
}

func (x *Hello) GetUdpToken() string {
	if x != nil {
		return x.UdpToken
	}
	return ""
}

type SubscriberUpdate struct {
	state  protoimpl.MessageState  `protogen:"open.v1"`
	Issi   uint32                  `protobuf:"varint,1,opt,name=issi,proto3" json:"issi,omitempty"`
	Action SubscriberUpdate_Action `protobuf:"varint,2,opt,name=action,proto3,enum=freetetra.federation.v2.SubscriberUpdate_Action" json:"action,omitempty"`
	// Current affiliations for ACTION_REGISTER.
	Gssis         []uint32 `protobuf:"varint,3,rep,packed,name=gssis,proto3" json:"gssis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriberUpdate) Reset() {
	*x = SubscriberUpdate{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriberUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberUpdate) ProtoMessage() {}

func (x *SubscriberUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberUpdate.ProtoReflect.Descriptor instead.
func (*SubscriberUpdate) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriberUpdate) GetIssi() uint32 {
	if x != nil {
		return x.Issi
	}
	return 0
}

func (x *SubscriberUpdate) GetAction() SubscriberUpdate_Action {
	if x != nil {
		return x.Action
	}
	return SubscriberUpdate_ACTION_UNSPECIFIED
}

func (x *SubscriberUpdate) GetGssis() []uint32 {
	if x != nil {
		return x.Gssis
	}
	return nil
}

type AffiliateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issi          uint32                 `protobuf:"varint,1,opt,name=issi,proto3" json:"issi,omitempty"`
	Action        AffiliateUpdate_Action `protobuf:"varint,2,opt,name=action,proto3,enum=freetetra.federation.v2.AffiliateUpdate_Action" json:"action,omitempty"`
	Gssis         []uint32               `protobuf:"varint,3,rep,packed,name=gssis,proto3" json:"gssis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffiliateUpdate) Reset() {
	*x = AffiliateUpdate{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffiliateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffiliateUpdate) ProtoMessage() {}

func (x *AffiliateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffiliateUpdate.ProtoReflect.Descriptor instead.
func (*AffiliateUpdate) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{4}
}

func (x *AffiliateUpdate) GetIssi() uint32 {
	if x != nil {
		return x.Issi
	}
	return 0
}

func (x *AffiliateUpdate) GetAction() AffiliateUpdate_Action {
	if x != nil {
		return x.Action
	}
	return AffiliateUpdate_ACTION_UNSPECIFIED
}

func (x *AffiliateUpdate) GetGssis() []uint32 {
	if x != nil {
		return x.Gssis
	}
	return nil
}

type CallStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SourceIssi    uint32                 `protobuf:"varint,2,opt,name=source_issi,json=sourceIssi,proto3" json:"source_issi,omitempty"`
	DestGssi      uint32                 `protobuf:"varint,3,opt,name=dest_gssi,json=destGssi,proto3" json:"dest_gssi,omitempty"`
	Priority      uint32                 `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Service       uint32                 `protobuf:"varint,5,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStart) Reset() {
	*x = CallStart{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStart) ProtoMessage() {}

func (x *CallStart) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStart.ProtoReflect.Descriptor instead.
func (*CallStart) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{5}
}

func (x *CallStart) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CallStart) GetSourceIssi() uint32 {
	if x != nil {
		return x.SourceIssi
	}
	return 0
}

func (x *CallStart) GetDestGssi() uint32 {
	if x != nil {
		return x.DestGssi
	}
	return 0
}

func (x *CallStart) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CallStart) GetService() uint32 {
	if x != nil {
		return x.Service
	}
	return 0
}

type CallEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cause         uint32                 `protobuf:"varint,2,opt,name=cause,proto3" json:"cause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEnd) Reset() {
	*x = CallEnd{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEnd) ProtoMessage() {}

func (x *CallEnd) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEnd.ProtoReflect.Descriptor instead.
func (*CallEnd) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{6}
}

func (x *CallEnd) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *CallEnd) GetCause() uint32 {
	if x != nil {
		return x.Cause
	}
	return 0
}

type VoiceFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID string form for 1:1 compatibility with existing code path.
	CallUuid      string `protobuf:"bytes,1,opt,name=call_uuid,json=callUuid,proto3" json:"call_uuid,omitempty"`
	FrameData     []byte `protobuf:"bytes,2,opt,name=frame_data,json=frameData,proto3" json:"frame_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoiceFrame) Reset() {
	*x = VoiceFrame{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoiceFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoiceFrame) ProtoMessage() {}

func (x *VoiceFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoiceFrame.ProtoReflect.Descriptor instead.
func (*VoiceFrame) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{7}
}

func (x *VoiceFrame) GetCallUuid() string {
	if x != nil {
		return x.CallUuid
	}
	return ""
}

func (x *VoiceFrame) GetFrameData() []byte {
	if x != nil {
		return x.FrameData
	}
	return nil
}

type SdsRelay struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceIssi uint32                 `protobuf:"varint,1,opt,name=source_issi,json=sourceIssi,proto3" json:"source_issi,omitempty"`
	DestIssi   uint32                 `protobuf:"varint,2,opt,name=dest_issi,json=destIssi,proto3" json:"dest_issi,omitempty"`
	// Raw SDS payload bytes (preferred over hex string in v1).
	SdsData       []byte `protobuf:"bytes,3,opt,name=sds_data,json=sdsData,proto3" json:"sds_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdsRelay) Reset() {
	*x = SdsRelay{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdsRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdsRelay) ProtoMessage() {}

func (x *SdsRelay) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdsRelay.ProtoReflect.Descriptor instead.
func (*SdsRelay) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{8}
}

func (x *SdsRelay) GetSourceIssi() uint32 {
	if x != nil {
		return x.SourceIssi
	}
	return 0
}

func (x *SdsRelay) GetDestIssi() uint32 {
	if x != nil {
		return x.DestIssi
	}
	return 0
}

func (x *SdsRelay) GetSdsData() []byte {
	if x != nil {
		return x.SdsData
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{9}
}

type SyncSubscriber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gssis         []uint32               `protobuf:"varint,1,rep,packed,name=gssis,proto3" json:"gssis,omitempty"`
	Callsign      string                 `protobuf:"bytes,2,opt,name=callsign,proto3" json:"callsign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSubscriber) Reset() {
	*x = SyncSubscriber{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSubscriber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSubscriber) ProtoMessage() {}

func (x *SyncSubscriber) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSubscriber.ProtoReflect.Descriptor instead.
func (*SyncSubscriber) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{10}
}

func (x *SyncSubscriber) GetGssis() []uint32 {
	if x != nil {
		return x.Gssis
	}
	return nil
}

func (x *SyncSubscriber) GetCallsign() string {
	if x != nil {
		return x.Callsign
	}
	return ""
}

type SyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keyed by decimal ISSI string for direct parity with current map shape.
	Subscribers   map[string]*SyncSubscriber `protobuf:"bytes,1,rep,name=subscribers,proto3" json:"subscribers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{11}
}

func (x *SyncResponse) GetSubscribers() map[string]*SyncSubscriber {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

type GossipPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipPeer) Reset() {
	*x = GossipPeer{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipPeer) ProtoMessage() {}

func (x *GossipPeer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipPeer.ProtoReflect.Descriptor instead.
func (*GossipPeer) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{12}
}

func (x *GossipPeer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GossipPeer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PeerExchange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*GossipPeer          `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerExchange) Reset() {
	*x = PeerExchange{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerExchange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerExchange) ProtoMessage() {}

func (x *PeerExchange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerExchange.ProtoReflect.Descriptor instead.
func (*PeerExchange) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{13}
}

func (x *PeerExchange) GetPeers() []*GossipPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type UsersDbOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersDbOffer) Reset() {
	*x = UsersDbOffer{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersDbOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersDbOffer) ProtoMessage() {}

func (x *UsersDbOffer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersDbOffer.ProtoReflect.Descriptor instead.
func (*UsersDbOffer) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{14}
}

func (x *UsersDbOffer) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *UsersDbOffer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UsersDbOffer) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UsersDbRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersDbRequest) Reset() {
	*x = UsersDbRequest{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersDbRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersDbRequest) ProtoMessage() {}

func (x *UsersDbRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersDbRequest.ProtoReflect.Descriptor instead.
func (*UsersDbRequest) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{15}
}

type PositionSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issi          uint32                 `protobuf:"varint,1,opt,name=issi,proto3" json:"issi,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Repeater      string                 `protobuf:"bytes,4,opt,name=repeater,proto3" json:"repeater,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionSample) Reset() {
	*x = PositionSample{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSample) ProtoMessage() {}

func (x *PositionSample) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSample.ProtoReflect.Descriptor instead.
func (*PositionSample) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{16}
}

func (x *PositionSample) GetIssi() uint32 {
	if x != nil {
		return x.Issi
	}
	return 0
}

func (x *PositionSample) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *PositionSample) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *PositionSample) GetRepeater() string {
	if x != nil {
		return x.Repeater
	}
	return ""
}

type StationUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kept dynamic to match existing station map payload.
	Station       *structpb.Struct `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StationUpdate) Reset() {
	*x = StationUpdate{}
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StationUpdate) ProtoMessage() {}

func (x *StationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StationUpdate.ProtoReflect.Descriptor instead.
func (*StationUpdate) Descriptor() ([]byte, []int) {
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP(), []int{17}
}

func (x *StationUpdate) GetStation() *structpb.Struct {
	if x != nil {
		return x.Station
	}
	return nil
}

var File_internal_federation_proto_v2_federation_v2_draft_proto protoreflect.FileDescriptor

const file_internal_federation_proto_v2_federation_v2_draft_proto_rawDesc = "" +
	"\n" +
	"6internal/federation/proto/v2/federation_v2_draft.proto\x12\x17freetetra.federation.v2\x1a\x1cgoogle/protobuf/struct.proto\"\x9b\x01\n" +
	"\vStreamFrame\x12<\n" +
	"\acontrol\x18\x01 \x01(\v2 .freetetra.federation.v2.ControlH\x00R\acontrol\x12F\n" +
	"\vvoice_frame\x18\x02 \x01(\v2#.freetetra.federation.v2.VoiceFrameH\x00R\n" +
	"voiceFrameB\x06\n" +
	"\x04body\"\xf3\b\n" +
	"\aControl\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\rR\x0fprotocolVersion\x12\x15\n" +
	"\x06msg_id\x18\x03 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03ttl\x18\x04 \x01(\x05R\x03ttl\x12\x12\n" +
	"\x04path\x18\x05 \x03(\tR\x04path\x126\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x1e.freetetra.federation.v2.HelloH\x00R\x05hello\x12X\n" +
	"\x11subscriber_update\x18\v \x01(\v2).freetetra.federation.v2.SubscriberUpdateH\x00R\x10subscriberUpdate\x12U\n" +
	"\x10affiliate_update\x18\f \x01(\v2(.freetetra.federation.v2.AffiliateUpdateH\x00R\x0faffiliateUpdate\x12C\n" +
	"\n" +
	"call_start\x18\r \x01(\v2\".freetetra.federation.v2.CallStartH\x00R\tcallStart\x12=\n" +
	"\bcall_end\x18\x0e \x01(\v2 .freetetra.federation.v2.CallEndH\x00R\acallEnd\x12@\n" +
	"\tsds_relay\x18\x0f \x01(\v2!.freetetra.federation.v2.SdsRelayH\x00R\bsdsRelay\x12I\n" +
	"\fsync_request\x18\x10 \x01(\v2$.freetetra.federation.v2.SyncRequestH\x00R\vsyncRequest\x12L\n" +
	"\rsync_response\x18\x11 \x01(\v2%.freetetra.federation.v2.SyncResponseH\x00R\fsyncResponse\x12L\n" +
	"\rpeer_exchange\x18\x12 \x01(\v2%.freetetra.federation.v2.PeerExchangeH\x00R\fpeerExchange\x12M\n" +
	"\x0eusers_db_offer\x18\x13 \x01(\v2%.freetetra.federation.v2.UsersDbOfferH\x00R\fusersDbOffer\x12S\n" +
	"\x10users_db_request\x18\x14 \x01(\v2'.freetetra.federation.v2.UsersDbRequestH\x00R\x0eusersDbRequest\x12R\n" +
	"\x0fposition_sample\x18\x15 \x01(\v2'.freetetra.federation.v2.PositionSampleH\x00R\x0epositionSample\x12O\n" +
	"\x0estation_update\x18\x16 \x01(\v2&.freetetra.federation.v2.StationUpdateH\x00R\rstationUpdateB\t\n" +
	"\apayload\"?\n" +
	"\x05Hello\x12\x19\n" +
	"\budp_addr\x18\x01 \x01(\tR\audpAddr\x12\x1b\n" +
	"\tudp_token\x18\x02 \x01(\tR\budpToken\"\xd4\x01\n" +
	"\x10SubscriberUpdate\x12\x12\n" +
	"\x04issi\x18\x01 \x01(\rR\x04issi\x12H\n" +
	"\x06action\x18\x02 \x01(\x0e20.freetetra.federation.v2.SubscriberUpdate.ActionR\x06action\x12\x14\n" +
	"\x05gssis\x18\x03 \x03(\rR\x05gssis\"L\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fACTION_REGISTER\x10\x01\x12\x15\n" +
	"\x11ACTION_DEREGISTER\x10\x02\"\xd4\x01\n" +
	"\x0fAffiliateUpdate\x12\x12\n" +
	"\x04issi\x18\x01 \x01(\rR\x04issi\x12G\n" +
	"\x06action\x18\x02 \x01(\x0e2/.freetetra.federation.v2.AffiliateUpdate.ActionR\x06action\x12\x14\n" +
	"\x05gssis\x18\x03 \x03(\rR\x05gssis\"N\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACTION_AFFILIATE\x10\x01\x12\x16\n" +
	"\x12ACTION_DEAFFILIATE\x10\x02\"\x93\x01\n" +
	"\tCallStart\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vsource_issi\x18\x02 \x01(\rR\n" +
	"sourceIssi\x12\x1b\n" +
	"\tdest_gssi\x18\x03 \x01(\rR\bdestGssi\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\x12\x18\n" +
	"\aservice\x18\x05 \x01(\rR\aservice\"3\n" +
	"\aCallEnd\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\rR\x05cause\"H\n" +
	"\n" +
	"VoiceFrame\x12\x1b\n" +
	"\tcall_uuid\x18\x01 \x01(\tR\bcallUuid\x12\x1d\n" +
	"\n" +
	"frame_data\x18\x02 \x01(\fR\tframeData\"c\n" +
	"\bSdsRelay\x12\x1f\n" +
	"\vsource_issi\x18\x01 \x01(\rR\n" +
	"sourceIssi\x12\x1b\n" +
	"\tdest_issi\x18\x02 \x01(\rR\bdestIssi\x12\x19\n" +
	"\bsds_data\x18\x03 \x01(\fR\asdsData\"\r\n" +
	"\vSyncRequest\"B\n" +
	"\x0eSyncSubscriber\x12\x14\n" +
	"\x05gssis\x18\x01 \x03(\rR\x05gssis\x12\x1a\n" +
	"\bcallsign\x18\x02 \x01(\tR\bcallsign\"\xd1\x01\n" +
	"\fSyncResponse\x12X\n" +
	"\vsubscribers\x18\x01 \x03(\v26.freetetra.federation.v2.SyncResponse.SubscribersEntryR\vsubscribers\x1ag\n" +
	"\x10SubscribersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.freetetra.federation.v2.SyncSubscriberR\x05value:\x028\x01\"2\n" +
	"\n" +
	"GossipPeer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"I\n" +
	"\fPeerExchange\x129\n" +
	"\x05peers\x18\x01 \x03(\v2#.freetetra.federation.v2.GossipPeerR\x05peers\"T\n" +
	"\fUsersDbOffer\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\"\x10\n" +
	"\x0eUsersDbRequest\"d\n" +
	"\x0ePositionSample\x12\x12\n" +
	"\x04issi\x18\x01 \x01(\rR\x04issi\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x1a\n" +
	"\brepeater\x18\x04 \x01(\tR\brepeater\"B\n" +
	"\rStationUpdate\x121\n" +
	"\astation\x18\x01 \x01(\v2\x17.google.protobuf.StructR\astation2r\n" +
	"\x15FederationTransportV2\x12Y\n" +
	"\aConnect\x12$.freetetra.federation.v2.StreamFrame\x1a$.freetetra.federation.v2.StreamFrame(\x010\x01BUZSgithub.com/freetetra/server/internal/federation/proto/federationv2pb;federationv2pbb\x06proto3"

var (
	file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescOnce sync.Once
	file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescData []byte
)

func file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescGZIP() []byte {
	file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescOnce.Do(func() {
		file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_federation_proto_v2_federation_v2_draft_proto_rawDesc), len(file_internal_federation_proto_v2_federation_v2_draft_proto_rawDesc)))
	})
	return file_internal_federation_proto_v2_federation_v2_draft_proto_rawDescData
}

var file_internal_federation_proto_v2_federation_v2_draft_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_federation_proto_v2_federation_v2_draft_proto_goTypes = []any{
	(SubscriberUpdate_Action)(0), // 0: freetetra.federation.v2.SubscriberUpdate.Action
	(AffiliateUpdate_Action)(0),  // 1: freetetra.federation.v2.AffiliateUpdate.Action
	(*StreamFrame)(nil),          // 2: freetetra.federation.v2.StreamFrame
	(*Control)(nil),              // 3: freetetra.federation.v2.Control
	(*Hello)(nil),                // 4: freetetra.federation.v2.Hello
	(*SubscriberUpdate)(nil),     // 5: freetetra.federation.v2.SubscriberUpdate
	(*AffiliateUpdate)(nil),      // 6: freetetra.federation.v2.AffiliateUpdate
	(*CallStart)(nil),            // 7: freetetra.federation.v2.CallStart
	(*CallEnd)(nil),              // 8: freetetra.federation.v2.CallEnd
	(*VoiceFrame)(nil),           // 9: freetetra.federation.v2.VoiceFrame
	(*SdsRelay)(nil),             // 10: freetetra.federation.v2.SdsRelay
	(*SyncRequest)(nil),          // 11: freetetra.federation.v2.SyncRequest
	(*SyncSubscriber)(nil),       // 12: freetetra.federation.v2.SyncSubscriber
	(*SyncResponse)(nil),         // 13: freetetra.federation.v2.SyncResponse
	(*GossipPeer)(nil),           // 14: freetetra.federation.v2.GossipPeer
	(*PeerExchange)(nil),         // 15: freetetra.federation.v2.PeerExchange
	(*UsersDbOffer)(nil),         // 16: freetetra.federation.v2.UsersDbOffer
	(*UsersDbRequest)(nil),       // 17: freetetra.federation.v2.UsersDbRequest
	(*PositionSample)(nil),       // 18: freetetra.federation.v2.PositionSample
	(*StationUpdate)(nil),        // 19: freetetra.federation.v2.StationUpdate
	nil,                          // 20: freetetra.federation.v2.SyncResponse.SubscribersEntry
	(*structpb.Struct)(nil),      // 21: google.protobuf.Struct
}
var file_internal_federation_proto_v2_federation_v2_draft_proto_depIdxs = []int32{
	3,  // 0: freetetra.federation.v2.StreamFrame.control:type_name -> freetetra.federation.v2.Control
	9,  // 1: freetetra.federation.v2.StreamFrame.voice_frame:type_name -> freetetra.federation.v2.VoiceFrame
	4,  // 2: freetetra.federation.v2.Control.hello:type_name -> freetetra.federation.v2.Hello
	5,  // 3: freetetra.federation.v2.Control.subscriber_update:type_name -> freetetra.federation.v2.SubscriberUpdate
	6,  // 4: freetetra.federation.v2.Control.affiliate_update:type_name -> freetetra.federation.v2.AffiliateUpdate
	7,  // 5: freetetra.federation.v2.Control.call_start:type_name -> freetetra.federation.v2.CallStart
	8,  // 6: freetetra.federation.v2.Control.call_end:type_name -> freetetra.federation.v2.CallEnd
	10, // 7: freetetra.federation.v2.Control.sds_relay:type_name -> freetetra.federation.v2.SdsRelay
	11, // 8: freetetra.federation.v2.Control.sync_request:type_name -> freetetra.federation.v2.SyncRequest
	13, // 9: freetetra.federation.v2.Control.sync_response:type_name -> freetetra.federation.v2.SyncResponse
	15, // 10: freetetra.federation.v2.Control.peer_exchange:type_name -> freetetra.federation.v2.PeerExchange
	16, // 11: freetetra.federation.v2.Control.users_db_offer:type_name -> freetetra.federation.v2.UsersDbOffer
	17, // 12: freetetra.federation.v2.Control.users_db_request:type_name -> freetetra.federation.v2.UsersDbRequest
	18, // 13: freetetra.federation.v2.Control.position_sample:type_name -> freetetra.federation.v2.PositionSample
	19, // 14: freetetra.federation.v2.Control.station_update:type_name -> freetetra.federation.v2.StationUpdate
	0,  // 15: freetetra.federation.v2.SubscriberUpdate.action:type_name -> freetetra.federation.v2.SubscriberUpdate.Action
	1,  // 16: freetetra.federation.v2.AffiliateUpdate.action:type_name -> freetetra.federation.v2.AffiliateUpdate.Action
	20, // 17: freetetra.federation.v2.SyncResponse.subscribers:type_name -> freetetra.federation.v2.SyncResponse.SubscribersEntry
	14, // 18: freetetra.federation.v2.PeerExchange.peers:type_name -> freetetra.federation.v2.GossipPeer
	21, // 19: freetetra.federation.v2.StationUpdate.station:type_name -> google.protobuf.Struct
	12, // 20: freetetra.federation.v2.SyncResponse.SubscribersEntry.value:type_name -> freetetra.federation.v2.SyncSubscriber
	2,  // 21: freetetra.federation.v2.FederationTransportV2.Connect:input_type -> freetetra.federation.v2.StreamFrame
	2,  // 22: freetetra.federation.v2.FederationTransportV2.Connect:output_type -> freetetra.federation.v2.StreamFrame
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_internal_federation_proto_v2_federation_v2_draft_proto_init() }
func file_internal_federation_proto_v2_federation_v2_draft_proto_init() {
	if File_internal_federation_proto_v2_federation_v2_draft_proto != nil {
		return
	}
	file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamFrame_Control)(nil),
		(*StreamFrame_VoiceFrame)(nil),
	}
	file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes[1].OneofWrappers = []any{
		(*Control_Hello)(nil),
		(*Control_SubscriberUpdate)(nil),
		(*Control_AffiliateUpdate)(nil),
		(*Control_CallStart)(nil),
		(*Control_CallEnd)(nil),
		(*Control_SdsRelay)(nil),
		(*Control_SyncRequest)(nil),
		(*Control_SyncResponse)(nil),
		(*Control_PeerExchange)(nil),
		(*Control_UsersDbOffer)(nil),
		(*Control_UsersDbRequest)(nil),
		(*Control_PositionSample)(nil),
		(*Control_StationUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_federation_proto_v2_federation_v2_draft_proto_rawDesc), len(file_internal_federation_proto_v2_federation_v2_draft_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_federation_proto_v2_federation_v2_draft_proto_goTypes,
		DependencyIndexes: file_internal_federation_proto_v2_federation_v2_draft_proto_depIdxs,
		EnumInfos:         file_internal_federation_proto_v2_federation_v2_draft_proto_enumTypes,
		MessageInfos:      file_internal_federation_proto_v2_federation_v2_draft_proto_msgTypes,
	}.Build()
	File_internal_federation_proto_v2_federation_v2_draft_proto = out.File
	file_internal_federation_proto_v2_federation_v2_draft_proto_goTypes = nil
	file_internal_federation_proto_v2_federation_v2_draft_proto_depIdxs = nil
}
