// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: internal/federation/proto/v2/federation_v2_draft.proto

package federationv2pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederationTransportV2_Connect_FullMethodName = "/freetetra.federation.v2.FederationTransportV2/Connect"
)

// FederationTransportV2Client is the client API for FederationTransportV2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FederationTransportV2 is a typed successor to the v1 envelope transport.
//
// Notes:
//   - One bidi stream carries both control and voice traffic.
//   - Authentication metadata can remain transport-level (headers/metadata),
//     while payload semantics are strongly typed.
type FederationTransportV2Client interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error)
}

type federationTransportV2Client struct {
	cc grpc.ClientConnInterface
}

func NewFederationTransportV2Client(cc grpc.ClientConnInterface) FederationTransportV2Client {
	return &federationTransportV2Client{cc}
}

func (c *federationTransportV2Client) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StreamFrame, StreamFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationTransportV2_ServiceDesc.Streams[0], FederationTransportV2_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFrame, StreamFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationTransportV2_ConnectClient = grpc.BidiStreamingClient[StreamFrame, StreamFrame]

// FederationTransportV2Server is the server API for FederationTransportV2 service.
// All implementations must embed UnimplementedFederationTransportV2Server
// for forward compatibility.
//
// FederationTransportV2 is a typed successor to the v1 envelope transport.
//
// Notes:
//   - One bidi stream carries both control and voice traffic.
//   - Authentication metadata can remain transport-level (headers/metadata),
//     while payload semantics are strongly typed.
type FederationTransportV2Server interface {
	Connect(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error
	mustEmbedUnimplementedFederationTransportV2Server()
}

// UnimplementedFederationTransportV2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationTransportV2Server struct{}

func (UnimplementedFederationTransportV2Server) Connect(grpc.BidiStreamingServer[StreamFrame, StreamFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedFederationTransportV2Server) mustEmbedUnimplementedFederationTransportV2Server() {}
func (UnimplementedFederationTransportV2Server) testEmbeddedByValue()                               {}

// UnsafeFederationTransportV2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationTransportV2Server will
// result in compilation errors.
type UnsafeFederationTransportV2Server interface {
	mustEmbedUnimplementedFederationTransportV2Server()
}

func RegisterFederationTransportV2Server(s grpc.ServiceRegistrar, srv FederationTransportV2Server) {
	// If the following call pancis, it indicates UnimplementedFederationTransportV2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederationTransportV2_ServiceDesc, srv)
}

func _FederationTransportV2_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FederationTransportV2Server).Connect(&grpc.GenericServerStream[StreamFrame, StreamFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationTransportV2_ConnectServer = grpc.BidiStreamingServer[StreamFrame, StreamFrame]

// FederationTransportV2_ServiceDesc is the grpc.ServiceDesc for FederationTransportV2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationTransportV2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "freetetra.federation.v2.FederationTransportV2",
	HandlerType: (*FederationTransportV2Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _FederationTransportV2_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/federation/proto/v2/federation_v2_draft.proto",
}
