// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.35.0
// source: internal/federation/proto/federation.proto

package federationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FederationTransport_Connect_FullMethodName = "/freetetra.federation.v1.FederationTransport/Connect"
)

// FederationTransportClient is the client API for FederationTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FederationTransportClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error)
}

type federationTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewFederationTransportClient(cc grpc.ClientConnInterface) FederationTransportClient {
	return &federationTransportClient{cc}
}

func (c *federationTransportClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Envelope, Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FederationTransport_ServiceDesc.Streams[0], FederationTransport_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationTransport_ConnectClient = grpc.BidiStreamingClient[Envelope, Envelope]

// FederationTransportServer is the server API for FederationTransport service.
// All implementations must embed UnimplementedFederationTransportServer
// for forward compatibility.
type FederationTransportServer interface {
	Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error
	mustEmbedUnimplementedFederationTransportServer()
}

// UnimplementedFederationTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFederationTransportServer struct{}

func (UnimplementedFederationTransportServer) Connect(grpc.BidiStreamingServer[Envelope, Envelope]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedFederationTransportServer) mustEmbedUnimplementedFederationTransportServer() {}
func (UnimplementedFederationTransportServer) testEmbeddedByValue()                             {}

// UnsafeFederationTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FederationTransportServer will
// result in compilation errors.
type UnsafeFederationTransportServer interface {
	mustEmbedUnimplementedFederationTransportServer()
}

func RegisterFederationTransportServer(s grpc.ServiceRegistrar, srv FederationTransportServer) {
	// If the following call pancis, it indicates UnimplementedFederationTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FederationTransport_ServiceDesc, srv)
}

func _FederationTransport_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FederationTransportServer).Connect(&grpc.GenericServerStream[Envelope, Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FederationTransport_ConnectServer = grpc.BidiStreamingServer[Envelope, Envelope]

// FederationTransport_ServiceDesc is the grpc.ServiceDesc for FederationTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FederationTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "freetetra.federation.v1.FederationTransport",
	HandlerType: (*FederationTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _FederationTransport_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/federation/proto/federation.proto",
}
